#pragma once

// AGENT-CTX: oauth_provider.h is the seam between AuthService and the two
// concrete OAuth2 providers (GitHub, Google). AuthService holds a map of
// provider_name → IOAuthProvider* and never depends on concrete types.
// When adding a new provider in a future slice, implement IOAuthProvider and
// register it in HttpServer — AuthService needs zero changes.
//
// The HttpGetFn / HttpPostFn injection points exist solely for unit testing
// without real network calls. Production code uses the curl_get / curl_post
// free functions defined in oauth_provider.cpp. Tests pass lambdas that
// return canned JSON.

#include <functional>
#include <optional>
#include <string>
#include <string_view>

#include "server/config.h"

namespace anjeer::server {

// AGENT-CTX: OAuthUserInfo carries the minimal identity returned by any
// provider after a successful code exchange + profile fetch.
// email is optional: GitHub users may set their email to private, in which
// case the /user endpoint returns null. Google always provides it when the
// email scope is granted.
// provider_id is the opaque identifier from the provider (never a username).
// username is the raw display name — AuthService sanitizes it before storing.
struct OAuthUserInfo {
    std::string                provider_id;
    std::string                username;
    std::optional<std::string> email;
};

// Injectable HTTP function types. Defaults to real libcurl in production;
// overridden with canned-response lambdas in unit tests.
using HttpGetFn  = std::function<std::string(std::string_view url,
                                              std::string_view bearer_token)>;
using HttpPostFn = std::function<std::string(std::string_view url,
                                              std::string_view body,
                                              std::string_view content_type)>;

// Production libcurl implementations — exposed so tests can selectively
// replace only one of the two if needed.
// AGENT-CTX: curl_global_init(CURL_GLOBAL_DEFAULT) must be called once in
// main() before any of these are invoked. Not called here to avoid the
// initialisation-order problem with static objects. See Task 11 / main.cpp.
std::string curl_get (std::string_view url, std::string_view bearer_token);
std::string curl_post(std::string_view url, std::string_view body,
                       std::string_view content_type);

class IOAuthProvider {
public:
    virtual ~IOAuthProvider() = default;

    // Returns the full redirect URL for the browser. state is a random per-
    // request nonce generated by HttpServer to prevent CSRF on the callback.
    virtual std::string  authorization_url(std::string_view state) const = 0;

    // Exchanges the authorisation code for a provider access token, then
    // fetches the user profile. Throws std::runtime_error on network failure
    // or error response from the provider.
    virtual OAuthUserInfo exchange_code(std::string_view code) = 0;

    virtual std::string_view provider_name() const = 0;
};

// ---------------------------------------------------------------------------
// GitHub
// ---------------------------------------------------------------------------
class GitHubOAuthProvider final : public IOAuthProvider {
public:
    explicit GitHubOAuthProvider(const ServerConfig::AuthConfig::OAuthProviderConfig& cfg,
                                  HttpGetFn  get_fn  = curl_get,
                                  HttpPostFn post_fn = curl_post);

    std::string   authorization_url(std::string_view state) const override;
    OAuthUserInfo exchange_code    (std::string_view code)        override;
    std::string_view provider_name()                        const override { return "github"; }

private:
    ServerConfig::AuthConfig::OAuthProviderConfig cfg_;
    HttpGetFn  get_;
    HttpPostFn post_;
};

// ---------------------------------------------------------------------------
// Google
// ---------------------------------------------------------------------------
class GoogleOAuthProvider final : public IOAuthProvider {
public:
    explicit GoogleOAuthProvider(const ServerConfig::AuthConfig::OAuthProviderConfig& cfg,
                                  HttpGetFn  get_fn  = curl_get,
                                  HttpPostFn post_fn = curl_post);

    std::string   authorization_url(std::string_view state) const override;
    OAuthUserInfo exchange_code    (std::string_view code)        override;
    std::string_view provider_name()                        const override { return "google"; }

private:
    ServerConfig::AuthConfig::OAuthProviderConfig cfg_;
    HttpGetFn  get_;
    HttpPostFn post_;
};

} // namespace anjeer::server
